-- 코드를 입력하세요 fwghso
SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF 
    LEFT JOIN ICECREAM_INFO
    ON FIRST_HALF.flavor = ICECREAM_INFO.flavor
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC

;